Force application to stay in portrait mode regardless of device orientation
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #11
Opened 2017-07-12 01:36 UTC by cdevan

This was a quick one so it should be fast to review

2017-07-12 03:21 UTC, JasonRitz approved these changes
easiest review yet :) the app now only works in portrait.

2017-07-12 03:26 UTC, lcc4 requested changes
Please add to the README documentation that the application only supports portrait mode.

2017-07-12 03:37 UTC, lcc4 commented
I ran it on my simulator, and it stayed in the fixed position. @JasonRitz were you able to try it on your phone?

2017-07-15 23:13 UTC, lcc4 approved these changes

2017-07-15 23:13 UTC, merged