Show projects
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #14
Opened 2017-07-15 23:36 UTC by dwagg

2017-07-16 01:34 UTC, cdevan approved these changes
Code looks good, projects appear as indicated. Projects match what appears in the Web site for me. Spacing is now fixed. May need to replace image at sponsor's behest.

2017-07-16 04:35 UTC, lcc4 requested changes
The code does not currently handle the loading of multiple result pages from the API as the user scrolls through the list of projects.

2017-07-16 05:25 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/ProjectListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
This function shows as 0% test coverage.  Can a test be written that calls it?

2017-07-16 05:25 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/ProjectListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
This function shows as 0% test coverage. Can a test be written that calls it?

2017-07-16 06:29 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/ProjectListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
@lcc4 added some tests to cover this and the other missing coverage. Extracted some code to a its own method since it is all related.

2017-07-17 03:19 UTC, lcc4 approved these changes
Code coverage improved. Runs fine and looks good.

2017-07-17 03:19 UTC, merged