View cycles
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #32
Opened 2017-07-23 20:44 UTC by dwagg

2017-07-23 21:29 UTC, whuiras approved these changes

2017-07-24 01:58 UTC, JasonRitz approved these changes
All looks good. Tests pass and the accordion view works as expected.

2017-07-24 02:12 UTC, lcc4 requested changes

2017-07-24 02:12 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestCycleListModel.swift
> +            if cycle["itemType"] as! Int != 36 || fields["testPlan"] as! Int != parentId{
@dwagg can you clarify why this has a hardcoded 36?

2017-07-24 02:13 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
>      // TO DO: attach this action to the selected plan button
Is this comment valid or out-of-date?

2017-07-24 02:18 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for JamaTests/TestCycleListModelUnitTests.swift
>      var testCycleItemType = 36
Is this why the hardcoded 36 above? To differentiate if it is a testCycle or not testCycle? Where did those numbers come from?

2017-07-24 02:21 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for JamaTests/TestCycleListModelUnitTests.swift
>      var testCycleItemType = 36
Yes I refactored it to be a constant that has a inline comment explaining the numbers. It is the Jama system ID for test cycles.

2017-07-24 02:26 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
>                      //reload Data in view? self.testCycle.reloadData()
what is this comment signaling? Is this work that needs to be done or is it out-of-date?

2017-07-24 02:42 UTC, lcc4 approved these changes

2017-07-24 02:48 UTC, merged