Login screen
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #4
Opened 2017-07-06 01:34 UTC by benleelawrence

Please review the login screen Jason and I created

2017-07-06 01:41 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama.xcodeproj/project.pbxproj
> +						DevelopmentTeam = LA4QFXA5C5;
Did you change the Development team on purpose? Did we need to?

2017-07-06 01:42 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama.xcodeproj/project.pbxproj
> +						DevelopmentTeam = LA4QFXA5C5;
I know this is a generated file but else where it appears the development team was changed

2017-07-06 01:46 UTC, benleelawrence commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama.xcodeproj/project.pbxproj
> +						DevelopmentTeam = LA4QFXA5C5;
I'm not sure if we need this, it wouldn't let me run the program on my iPhone until I changed the Bundle Identifier, I think that's what this is

2017-07-06 01:48 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/MaxTextLength.swift
> +import Foundation
I think this file should be moved into the utils file and out of the viewController file. and we should write a test or two to make sure this is working.

2017-07-06 01:52 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama.xcodeproj/project.pbxproj
> +						DevelopmentTeam = LA4QFXA5C5;
Okay, I'm not sure the best way for all that to happen is, iOS code signing is confusing. But thats fine, it is still working for me, and it runs on your device. I suspect we will end up revisiting this but for now this is good enough for me.

2017-07-06 02:21 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/MaxTextLength.swift
> +import Foundation
@benleelawrence @JasonRitz I am not sure if you guys saw this comment. What are your thoughts on it. I meant "utils folder" and "ViewControllers" folder in above comment.

2017-07-06 02:30 UTC, JasonRitz commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/MaxTextLength.swift
> +import Foundation
I moved the file to utils, but don't know what\how to write tests for it. the code adds a max length field in the attributes inspector in Xcode. so it doesn't effect our app but Xcode.

2017-07-06 04:10 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/MaxTextLength.swift
> +import Foundation
Works for me.

2017-07-06 04:19 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/MaxTextLength.swift
> +import Foundation
done

2017-07-06 04:25 UTC, dwagg requested changes
There is a label on the Login View that says "Log In" but it is not needed as we have to title of the screen in the navigation bar.

2017-07-06 04:45 UTC, dwagg approved these changes

2017-07-06 05:05 UTC, mmcbee1 commented
Just a suggestion to center the group of input fields: make another view to hold the input fields and login button, then center that vertically/horizontally with the main screen view (centerX and centerY). You would only need to do the leading and trailing margins once for the new view, instead of for each text box, and this would center it for all screen sizes and landscape, too. Then you could pad the space between input fields like we did in the TDD tutorial.

Otherwise great job! Yay we have our first screen!

2017-07-07 03:15 UTC, mmcbee1 approved these changes

2017-07-07 04:20 UTC, lcc4 requested changes
This branch is now behind master, so please, in addition to fixing the merge conflict, merge master into this branch and ensure the build still succeeds.  I cannot complete the merge until this happens.

2017-07-07 06:53 UTC, dwagg requested changes
Could we move the "instance" text field into the new wrapper view with the other elements?

2017-07-07 22:36 UTC, dwagg approved these changes

2017-07-07 23:47 UTC, lcc4 approved these changes

2017-07-07 23:52 UTC, merged