Undo step
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #53
Opened 2017-08-06 23:12 UTC by dwagg

2017-08-06 23:14 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/Base.lproj/Main.storyboard
> +                    <navigationItem key="navigationItem" title="Test Run" id="Bjc-ta-NLl">
I changed the title on the index page to match the back button on the step detail page. It also makes it less crowded on smaller screens. Not 100% if this is what we want to do though. Any input would be great.

2017-08-06 23:39 UTC, JasonRitz requested changes
The Input results in the pop up text box does not clear when the user hits "cancel Run"

2017-08-07 00:42 UTC, JasonRitz approved these changes

2017-08-07 00:51 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestStepViewController.swift
> +            //TODO reset the Results field for the step
Does this still need to be done?

2017-08-07 01:30 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestStepViewController.swift
> +            //TODO reset the Results field for the step
Nope, I have updated this

2017-08-07 02:27 UTC, lcc4 commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/Base.lproj/Main.storyboard
> +                    <navigationItem key="navigationItem" title="Test Run" id="Bjc-ta-NLl">
I think it is fine.  If Jama wants us to change it, we will.

2017-08-07 04:19 UTC, merged