Cycle bug fix
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #57
Opened 2017-08-09 15:34 UTC by cdevan

This is not a polished PR, just want to open it to get feedback

2017-08-10 17:40 UTC, benleelawrence approved these changes
Tested this for every scenario I could think of and it works correctly, ready to merge.

2017-08-11 22:18 UTC, dwagg requested changes
Can we remove the first calls to reloadData in the Cycles and Runs sections of this method and I have added a note about a comment that was not moved when the block of code it refers to was moved. If we can fix that also.

2017-08-11 22:20 UTC, dwagg commented
There is a comment in the .run section that says "if there are no runs, display an empty run with the default value set to No Runs Found, made unclickable and with no number in the buildRunCell function below" can we move that down to just above the code it is referring to.

2017-08-12 02:10 UTC, dwagg approved these changes

2017-08-12 02:11 UTC, merged