Added function scrollToLastRow to make cycle cell visible automatical…
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #68
Opened 2017-08-13 21:08 UTC by benleelawrence

…ly on the last test plan

2017-08-14 19:49 UTC, JasonRitz approved these changes
Everything looks and works as it should. Good Job!

2017-08-14 21:11 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
> +                    self.testList.reloadData()
Is this call needed? If not can we get rid of it. If it is needed can we get rid of the call in the if statement 2 lines up.

2017-08-14 21:12 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
> +                }
This curly brace is at the wrong level of indentation.

2017-08-14 21:13 UTC, dwagg requested changes
I added a couple of comments to the changes, could you take a look and see if those changes make sense?

2017-08-15 01:21 UTC, dwagg approved these changes

2017-08-15 01:24 UTC, merged