added run name to the success popup
CapstoneTeamA/Mobile-Test-Runner-for-Jama pull request #85
Opened 2017-08-18 07:51 UTC by dwagg

2017-08-18 07:56 UTC, benleelawrence commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
> +            let updateSuccededAlert = UIAlertController(title: updatedRunName + " updated", message: updatedRunName + " was successfully committed.", preferredStyle: UIAlertControllerStyle.alert)
Succeed misspelled

2017-08-18 08:07 UTC, dwagg commented on Mobile Test Runner for Jama/Mobile Test Runner for Jama/TestListViewController.swift
> +            let updateSucceededAlert = UIAlertController(title: updatedRunName + " updated", message: updatedRunName + " was successfully committed.", preferredStyle: UIAlertControllerStyle.alert)
I am not sure if we want the run name in the title and body, just the title or just the body. I went with both but I am not 100% sure that is the right way to go. Especially when there are long run names.

2017-08-18 08:08 UTC, benleelawrence commented
Before this update I kind of thought the success popup stayed onscreen for too long, but now for really long test run names we might want to add another second.  Another idea would be to only display the test run name once, e.g., title: " Test Run updated", message: updatedRunName + " was successfully committed." or the other way around

2017-08-18 08:14 UTC, dwagg commented
Do we want to move away from a timer and just put a dismiss button on the popup? That way the user decides how long the popup sticks around.

2017-08-18 18:25 UTC, lcc4 commented
I like Ben's idea of the popup containing the message:  
" Test Run updated", message: updatedRunName + " was successfully committed."

And allowing the user to dismiss the popup. Want to try implementing those changes?

2017-08-18 20:59 UTC, lcc4 requested changes
Please modify the popup per Ben's suggestions.

2017-08-19 01:37 UTC, lcc4 approved these changes

2017-08-19 01:38 UTC, merged